name: flutter_interview_tast
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.33
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.4
  json_annotation: ^4.9.0
  go_router: ^16.0.0

  #Image caching
  cached_network_image: ^3.4.1

  #svg image viewer
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.1
  build_runner: ^2.4.15
  json_serializable: ^6.10.0
  mocktail: ^1.0.4
  mockito: ^5.5.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/