// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAugswshHPd4HWGgJY5Og0hVHRHQ9gwqfM',
    appId: '1:67563122424:web:f7b3eeff43dd01ec33d50d',
    messagingSenderId: '67563122424',
    projectId: 'flutter-interview-task-15fb3',
    authDomain: 'flutter-interview-task-15fb3.firebaseapp.com',
    storageBucket: 'flutter-interview-task-15fb3.firebasestorage.app',
    measurementId: 'G-VCQ321WEHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj5e9RMBlcXTfQ7Tt9KxmLXi3ZLbkPtmM',
    appId: '1:67563122424:android:26a118f7338e8cbc33d50d',
    messagingSenderId: '67563122424',
    projectId: 'flutter-interview-task-15fb3',
    storageBucket: 'flutter-interview-task-15fb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARV7Dn4GhczDP5wFGqoVpMGNwRFsksnYU',
    appId: '1:67563122424:ios:19fea8e2513e417c33d50d',
    messagingSenderId: '67563122424',
    projectId: 'flutter-interview-task-15fb3',
    storageBucket: 'flutter-interview-task-15fb3.firebasestorage.app',
    iosBundleId: 'com.example.flutterInterviewTast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARV7Dn4GhczDP5wFGqoVpMGNwRFsksnYU',
    appId: '1:67563122424:ios:19fea8e2513e417c33d50d',
    messagingSenderId: '67563122424',
    projectId: 'flutter-interview-task-15fb3',
    storageBucket: 'flutter-interview-task-15fb3.firebasestorage.app',
    iosBundleId: 'com.example.flutterInterviewTast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAugswshHPd4HWGgJY5Og0hVHRHQ9gwqfM',
    appId: '1:67563122424:web:d8b0d45b0dddb5e633d50d',
    messagingSenderId: '67563122424',
    projectId: 'flutter-interview-task-15fb3',
    authDomain: 'flutter-interview-task-15fb3.firebaseapp.com',
    storageBucket: 'flutter-interview-task-15fb3.firebasestorage.app',
    measurementId: 'G-J6RZR6YDBC',
  );
}
